resources:
  - type: storage.v1.bucket
    name: sls-gcf-nodejs-dev-1507295001299
  - type: cloudfunctions.v1beta2.function
    name: gcf-nodejs-dev-first
    properties:
      location: us-central1
      availableMemoryMb: 256
      timeout: 60s
      function: http
      sourceArchiveUrl: >-
        gs://sls-gcf-nodejs-dev-1507295001299/serverless/gcf-nodejs/dev/1507318560752-2017-10-06T19:36:00.752Z/gcf-nodejs.zip
      httpsTrigger:
        url: path
